USE treinamento

SELECT P.NMPRODUCT AS 'Nome produto',
COUNT(PR.CDPRODUCT) AS 'Vezes que foi pedido',
COUNT(PR.CDPRODUCT)*PR.QTAMOUNT AS 'Quantidade total pedida'
FROM  PRODUCTREQUEST AS PR
INNER JOIN PRODUCT AS P
ON PR.CDPRODUCT=P.CDPRODUCT
INNER JOIN REQUEST AS R
ON PR.CDREQUEST=R.CDREQUEST
GROUP BY P.NMPRODUCT, PR.QTAMOUNT
HAVING COUNT(PR.CDPRODUCT)>=2