USE treinamento

SELECT DISTINCT P.NMPRODUCT AS 'Nome do produto'
FROM PRODUCTREQUEST AS PR
INNER JOIN PRODUCT AS P
ON PR.CDPRODUCT=P.CDPRODUCT
INNER JOIN REQUEST AS R
ON PR.CDREQUEST=R.CDREQUEST

SELECT P.NMPRODUCT AS 'Nome do produto'
FROM PRODUCTREQUEST AS PR
INNER JOIN PRODUCT AS P
ON PR.CDPRODUCT=P.CDPRODUCT
INNER JOIN REQUEST AS R
ON PR.CDREQUEST=R.CDREQUEST
GROUP BY P.NMPRODUCT