USE treinamento

SELECT R.DTREQUEST AS 'Data do pedido',
C.NMCUSTOMER AS 'Nome cliente',
COUNT(PR.CDPRODUCT) AS 'Produtos distintos pedidos',
SUM(PR.QTAMOUNT*PR.VLUNITARY) AS 'Valor total',
AVG(PR.QTAMOUNT*PR.VLUNITARY) AS 'Média dos valores'
FROM PRODUCTREQUEST AS PR
INNER JOIN REQUEST AS R
ON PR.CDREQUEST=R.CDREQUEST
INNER JOIN CUSTOMER AS C
ON R.CDCUSTOMER=C.CDCUSTOMER
GROUP BY C.NMCUSTOMER, R.DTREQUEST
ORDER BY 'Produtos distintos pedidos'