USE treinamento

SELECT C.NMCUSTOMER AS 'Nome cliente',
P.NMPRODUCT AS 'Nome produto',
COUNT(PR.CDPRODUCT)*PR.VLUNITARY*PR.QTAMOUNT AS 'Valor gasto',
COUNT(PR.CDPRODUCT) AS 'Quantas vezes foi pedido',
S.NMSUPPLIER AS 'Nome fornecedor'
FROM PRODUCTREQUEST AS PR
INNER JOIN REQUEST AS R
ON PR.CDREQUEST=R.CDREQUEST
INNER JOIN CUSTOMER AS C
ON R.CDCUSTOMER=R.CDCUSTOMER
INNER JOIN PRODUCT AS P
ON PR.CDPRODUCT=P.CDPRODUCT
INNER JOIN SUPPLIER AS S
ON P.CDSUPPLIER=S.CDSUPPLIER
GROUP BY C.NMCUSTOMER, P.NMPRODUCT, PR.VLUNITARY, PR.QTAMOUNT, S.NMSUPPLIER
HAVING COUNT(PR.CDPRODUCT)*PR.VLUNITARY*PR.QTAMOUNT>1000
ORDER BY C.NMCUSTOMER, P.NMPRODUCT