USE treinamento

SELECT P.NMPRODUCT AS 'Nome produto',
COUNT(P.NMPRODUCT) AS 'Vezes que foi pedido',
PR.QTAMOUNT*COUNT(P.NMPRODUCT) AS 'Quantidade total pedida'
FROM PRODUCTREQUEST AS PR
INNER JOIN PRODUCT AS P
ON PR.CDPRODUCT=P.CDPRODUCT
INNER JOIN REQUEST AS R
ON PR.CDREQUEST=R.CDREQUEST
GROUP BY P.NMPRODUCT, PR.QTAMOUNT