USE treinamento

SELECT P.NMPRODUCT AS 'Nome produto',
P.VLPRICE AS 'Preço produto',
S.NMSUPPLIER AS 'Nome fornecedor'
FROM PRODUCT AS P
INNER JOIN SUPPLIER AS S
ON P.CDSUPPLIER=S.CDSUPPLIER
WHERE S.NMSUPPLIER LIKE '%ICA%'
ORDER BY S.NMSUPPLIER, P.VLPRICE