USE treinamento

SELECT C.NMCUSTOMER AS 'Nome cliente',
P.NMPRODUCT AS 'Nome produto',
R.DTREQUEST AS 'Data do pedido',
R.DTDELIVER AS 'Data de entrega',
PR.QTAMOUNT AS 'Quantidade pedida',
PR.VLUNITARY AS 'Valor unitário',
R.VLTOTAL AS 'Valor total'
FROM PRODUCTREQUEST AS PR
INNER JOIN REQUEST AS R
ON PR.CDREQUEST=R.CDREQUEST
INNER JOIN PRODUCT AS P
ON PR.CDPRODUCT=P.CDPRODUCT
INNER JOIN CUSTOMER AS C
ON R.CDCUSTOMER=C.CDCUSTOMER
WHERE R.DTREQUEST>='2003/08/01' AND R.DTREQUEST<'2003/09/01'
AND P.NMPRODUCT LIKE 'M%'
GROUP BY C.NMCUSTOMER, P.NMPRODUCT, R.DTREQUEST, R.DTDELIVER, PR.QTAMOUNT, PR.VLUNITARY, R.VLTOTAL
HAVING SUM(PR.QTAMOUNT)<600