USE treinamento

SELECT P.NMPRODUCT AS 'Nome produto',
S.NMSUPPLIER AS 'Nome fornecedor',
P.VLPRICE AS 'Preço produto',
P.VLPRICE*0.9 AS 'Preço 10%OFF',
P.VLPRICE*0.8 AS 'Preço 20%OFF',
P.VLPRICE*0.7 AS 'Preço 30%OFF'
FROM PRODUCT AS P
INNER JOIN SUPPLIER AS S
ON P.CDSUPPLIER=S.CDSUPPLIER
WHERE P.VLPRICE*0.9>15
ORDER BY P.VLPRICE, P.NMPRODUCT