USE treinamento

SELECT P.NMPRODUCT AS 'Nome produto',
S.NMSUPPLIER AS 'Nome fornecedor',
P.VLPRICE AS 'Valor produto',
P.VLPRICE*P.QTSTOCK AS 'Preço do estoque',
P.VLPRICE*P.QTSTOCK*2 AS 'Preço do estoque 2x'
FROM PRODUCT AS P
INNER JOIN SUPPLIER AS S
ON P.CDSUPPLIER=S.CDSUPPLIER
WHERE P.VLPRICE*P.QTSTOCK>12000
ORDER BY S.NMSUPPLIER, NMPRODUCT