USE treinamento

SELECT S.NMSUPPLIER AS 'Nome fornecedor',
S.IDFONE AS 'Telefone fornecedor',
P.NMPRODUCT AS 'Nome produto',
P.VLPRICE AS 'Preço produto',
P.VLPRICE*P.QTSTOCK AS 'Preço estoque'
FROM PRODUCT AS P
INNER JOIN SUPPLIER AS S
ON P.CDSUPPLIER=S.CDSUPPLIER
WHERE P.NMPRODUCT LIKE 'S%'
AND P.VLPRICE>50
ORDER BY S.NMSUPPLIER, P.VLPRICE