USE treinamento

SELECT P.NMPRODUCT AS 'Nome produto',
C.NMCUSTOMER AS 'Nome cliente',
COUNT(PR.CDPRODUCT) AS 'Vezes comprado',
SUM(PR.QTAMOUNT) AS 'Quantidade total comprada',
SUM(PR.QTAMOUNT)*PR.VLUNITARY AS 'Valor total pago pelo produto'
FROM PRODUCTREQUEST AS PR
INNER JOIN PRODUCT AS P
ON PR.CDPRODUCT=P.CDPRODUCT
INNER JOIN REQUEST AS R
ON PR.CDREQUEST=R.CDREQUEST
INNER JOIN CUSTOMER AS C
ON R.CDCUSTOMER=C.CDCUSTOMER
GROUP BY C.NMCUSTOMER, P.NMPRODUCT, PR.VLUNITARY