USE treinamento

SELECT C.NMCUSTOMER AS 'Nome cliente',
COUNT(C.CDCUSTOMER) AS 'Numero de pedidos',
SUM(R.VLTOTAL) AS 'Total comprado'
FROM REQUEST AS R
INNER JOIN CUSTOMER AS C
ON R.CDCUSTOMER=C.CDCUSTOMER
WHERE R.DTREQUEST>='2003/01/01' AND R.DTREQUEST<'2004/01/01'
GROUP BY C.NMCUSTOMER