USE treinamento

UPDATE PRODUCT
SET VLPRICE=(SELECT AVG(VLUNITARY)
FROM PRODUCTREQUEST)
FROM PRODUCTREQUEST AS PR
RIGHT JOIN PRODUCT AS P
ON PR.CDPRODUCT=P.CDPRODUCT
WHERE P.CDPRODUCT IN
(
SELECT CDPRODUCT
FROM PRODUCTREQUEST
GROUP BY CDPRODUCT, QTAMOUNT
HAVING COUNT(CDPRODUCT)*QTAMOUNT<800
)
OR PR.CDREQUEST IS NULL