USE treinamento

SELECT S.NMSUPPLIER AS 'Nome fornecedor',
P.NMPRODUCT AS 'Nome produto',
COUNT(PR.CDPRODUCT) AS 'Total vendidos'
FROM PRODUCTREQUEST AS PR
RIGHT JOIN PRODUCT AS P
ON PR.CDPRODUCT=P.CDPRODUCT
RIGHT JOIN SUPPLIER AS S
ON P.CDSUPPLIER=S.CDSUPPLIER
GROUP BY P.NMPRODUCT, S.NMSUPPLIER

UNION ALL

SELECT SQ.NOME,
'Total vendido',
SUM(SQ.TOTAL) FROM (
SELECT S.NMSUPPLIER AS NOME,
P.NMPRODUCT AS 'Nome produto',
COUNT(PR.CDPRODUCT) AS TOTAL
FROM PRODUCTREQUEST AS PR
RIGHT JOIN PRODUCT AS P
ON PR.CDPRODUCT=P.CDPRODUCT
RIGHT JOIN SUPPLIER AS S
ON P.CDSUPPLIER=S.CDSUPPLIER
GROUP BY P.NMPRODUCT, S.NMSUPPLIER
) AS SQ
GROUP BY SQ.NOME

UNION ALL

SELECT 'Total geral',
'Total geral',
SUM(SQT.TOTAL) FROM (
SELECT SUM(SQ.TOTAL) AS TOTAL FROM (
SELECT S.NMSUPPLIER AS NOME,
P.NMPRODUCT AS 'Nome produto',
COUNT(PR.CDPRODUCT) AS TOTAL
FROM PRODUCTREQUEST AS PR
RIGHT JOIN PRODUCT AS P
ON PR.CDPRODUCT=P.CDPRODUCT
RIGHT JOIN SUPPLIER AS S
ON P.CDSUPPLIER=S.CDSUPPLIER
GROUP BY P.NMPRODUCT, S.NMSUPPLIER
) AS SQ
GROUP BY SQ.NOME
) AS SQT