USE treinamento

SELECT S.NMSUPPLIER AS 'Nome fornecedor',
S.IDFONE AS 'Telefone'
FROM SUPPLIER AS S
INNER JOIN PRODUCT AS P
ON S.CDSUPPLIER=P.CDSUPPLIER
WHERE P.NMPRODUCT='leite em po' OR P.NMPRODUCT='agua mineral'