USE treinamento

SELECT C.NMCUSTOMER AS 'Nome cliente',
P.NMPRODUCT AS 'Nome produto',
SUM(PR.VLUNITARY*PR.QTAMOUNT) AS 'Total gasto'
FROM PRODUCTREQUEST AS PR
INNER JOIN PRODUCT AS P
ON PR.CDPRODUCT=P.CDPRODUCT
INNER JOIN REQUEST AS R
ON PR.CDREQUEST=R.CDREQUEST
INNER JOIN CUSTOMER AS C
ON R.CDCUSTOMER=C.CDCUSTOMER
GROUP BY P.NMPRODUCT, C.NMCUSTOMER

UNION ALL

SELECT SQ.NOME,
'Total gasto',
SUM(SQ.TOTAL)
FROM (
SELECT C.NMCUSTOMER AS NOME,
SUM(PR.VLUNITARY*PR.QTAMOUNT) AS TOTAL
FROM PRODUCTREQUEST AS PR
INNER JOIN REQUEST AS R
ON PR.CDREQUEST=R.CDREQUEST
INNER JOIN CUSTOMER AS C
ON R.CDCUSTOMER=C.CDCUSTOMER
GROUP BY C.NMCUSTOMER
) AS SQ
GROUP BY SQ.NOME

UNION ALL

SELECT 'Total geral',
'Total geral',
SUM(SQT.TOTAL)
FROM
(
SELECT SUM(SQ.TOTAL) AS TOTAL
FROM (
SELECT SUM(PR.VLUNITARY*PR.QTAMOUNT) AS TOTAL
FROM PRODUCTREQUEST AS PR
INNER JOIN REQUEST AS R
ON PR.CDREQUEST=R.CDREQUEST
INNER JOIN CUSTOMER AS C
ON R.CDCUSTOMER=C.CDCUSTOMER
GROUP BY C.NMCUSTOMER
) AS SQ
) AS SQT