USE treinamento 

SELECT P.NMPRODUCT AS 'Nome produto',
COUNT(PR.CDPRODUCT) AS 'Quantas vezes foi vendido'
FROM PRODUCT AS P
LEFT JOIN PRODUCTREQUEST AS PR
ON P.CDPRODUCT=PR.CDPRODUCT
GROUP BY P.NMPRODUCT