USE LISTA01

ALTER TABLE PRODUCTREQUEST
ADD CONSTRAINT FKPRODUCTREQPRODUCT FOREIGN KEY (CDPRODUCT) REFERENCES PRODUCT

ALTER TABLE PRODUCTREQUEST
ADD CONSTRAINT FKPRODUCTREQREQUEST FOREIGN KEY (CDREQUEST) REFERENCES REQUEST

ALTER TABLE REQUEST
ADD CONSTRAINT FKREQUESTCUSTOMER FOREIGN KEY (CDCUSTOMER) REFERENCES CUSTOMER

ALTER TABLE PRODUCT
ADD CONSTRAINT FKPRODUCTSUPPLIER FOREIGN KEY (CDSUPPLIER) REFERENCES SUPPLIER