USE LISTA01

ALTER TABLE PRODUCTREQUEST
ADD CONSTRAINT PKPRODUCTREQUEST PRIMARY KEY (CDREQUEST,CDPRODUCT)

ALTER TABLE PRODUCT
ADD CONSTRAINT PKPRODUCT PRIMARY KEY (CDPRODUCT)

ALTER TABLE REQUEST
ADD CONSTRAINT PKREQUEST PRIMARY KEY (CDREQUEST)

ALTER TABLE CUSTOMER
ADD CONSTRAINT PKCUSTOMER PRIMARY KEY (CDCUSTOMER)

ALTER TABLE SUPPLIER
ADD CONSTRAINT PKSUPPLIER PRIMARY KEY (CDSUPPLIER)
