USE LISTA01

CREATE TABLE PRODUCTREQUEST (
CDREQUEST NUMERIC(10,0) NOT NULL,
CDPRODUCT NUMERIC(10,0) NOT NULL,
QTAMOUNT NUMERIC(10,0),
VLUNITARY NUMERIC(18,8) NOT NULL
)

CREATE TABLE REQUEST (
CDREQUEST NUMERIC(10,0) NOT NULL,
DTREQUEST DATETIME,
CDCUSTOMER NUMERIC(10,0) NOT NULL,
DTDELIVER DATETIME,
VLTOTAL NUMERIC(18,8)
)

CREATE TABLE PRODUCT (
CDPRODUCT NUMERIC(10,0) NOT NULL,
NMPRODUCT VARCHAR(255),
CDSUPPLIER NUMERIC(10,0) NOT NULL,
VLPRICE NUMERIC(18,8) NOT NULL,
QTSTOCK NUMERIC(10,0)
)

CREATE TABLE CUSTOMER (
CDCUSTOMER NUMERIC(10,0) NOT NULL,
NMCUSTOMER VARCHAR(255),
NRFONE VARCHAR(50),
DSADRESS VARCHAR(255)
)

CREATE TABLE SUPPLIER (
CDSUPPLIER NUMERIC(10,0) NOT NULL,
NMSUPPLIER VARCHAR(255),
NRFONE VARCHAR(50)
)