USE treinamento

SELECT C.NMCUSTOMER AS 'Nome cliente',
P.NMPRODUCT AS 'Nome produto',
R.DTREQUEST AS 'Data do pedido',
R.VLTOTAL/PR.VLUNITARY AS  'Quantidade pedida',
PR.VLUNITARY AS 'Valor unitário',
R.VLTOTAL AS 'Valor total'
FROM PRODUCTREQUEST AS PR
INNER JOIN REQUEST AS R
ON PR.CDREQUEST=R.CDREQUEST
INNER JOIN PRODUCT AS P
ON PR.CDPRODUCT=P.CDPRODUCT
INNER JOIN CUSTOMER AS C
ON R.CDCUSTOMER=C.CDCUSTOMER
WHERE R.VLTOTAL/PR.VLUNITARY>=500