USE treinamento

SELECT C.NMCUSTOMER AS 'Nome cliente',
R.DTREQUEST AS 'Data do pedido',
VLTOTAL AS 'Valor total'
FROM CUSTOMER AS C
INNER JOIN REQUEST AS R
ON C.CDCUSTOMER=R.CDCUSTOMER
WHERE R.DTREQUEST>='2003/06/01' AND R.DTREQUEST<='2003/07/01'