USE treinamento

SELECT P.NMPRODUCT AS 'Nome produto',
S.NMSUPPLIER AS 'Nome fornecedor',
S.IDFONE AS 'Telefone fornecedor'
FROM PRODUCT AS P
INNER JOIN SUPPLIER AS S
ON P.CDSUPPLIER=S.CDSUPPLIER
WHERE P.VLPRICE>20 AND P.QTSTOCK>1500