USE treinamento

INSERT INTO PRODUCTREQUEST
SELECT R.CDREQUEST, P.CDPRODUCT, 10 AS QT, P.VLPRICE
FROM PRODUCTREQUEST AS PR
INNER JOIN REQUEST AS R
ON PR.CDREQUEST=R.CDREQUEST
INNER JOIN PRODUCT AS P
ON PR.CDPRODUCT=P.CDPRODUCT
WHERE PR.CDREQUEST=R.CDREQUEST
AND PR.CDPRODUCT=P.CDPRODUCT